spring.application.name=demo-ecom


#spring.datasource.url=jdbc:h2:mem:test
#spring.datasource.url=jdbc:h2:file:./data/mydb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=kiran
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=create-drop

# swagger configuration
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

project.image=images/
spring.security.user.password=pass123

spring.app.jwtSecretKey=mySecretKey123917238as234sadfwfasdfwerasdfasdfawuelaldjflajeorweor
spring.app.jswTokenExpirationTime=3000000
spring.app.jwtCookieName=springBootECom

logging.level.root=DEBUG
logging.exception-conversion-word=%wEx
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG
server.error.include-stacktrace=always

# MySQL Connection
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=Polas@1982
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.diaelect=org.hibernate.dialect.MySQLDialect

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Polas@1982

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect