spring.application.name=demo-ecom
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=kiran

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=create-drop

# swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs